[package]
name = "archive"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
clap = { version = "4.5.26", features = ["derive"] }
arboard = "3.4.1"