[package]
name = "rq"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
clap = { version = "4.5.26", features = ["derive"] }
anyhow = "1.0"
